

"""initial_tables

Revision ID: 001_initial_tables
Revises: 
Create Date: 2025-08-28 05:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001_initial_tables'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - would be adjusted ###
    op.create_table('rfps',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('project_id', sa.String(), nullable=True),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('text_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('compliance_findings',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rfp_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('rule_category', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('citation_text', sa.Text(), nullable=False),
    sa.Column('citation_start', sa.Integer(), nullable=True),
    sa.Column('citation_end', sa.Integer(), nullable=True),
    sa.Column('suggested_fix', sa.Text(), nullable=True),
    sa.Column('ruleset_version', sa.String(), nullable=False),
    sa.Column('is_llm_generated', sa.Boolean(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimates',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('rfp_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('location_factor', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rfp_id'], ['rfps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estimate_lines',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('estimate_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('finding_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('csi_code', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.Column('total_cost', sa.Float(), nullable=False),
    sa.Column('is_custom', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['estimate_id'], ['estimates.id'], ),
    sa.ForeignKeyConstraint(['finding_id'], ['compliance_findings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - would be adjusted ###
    op.drop_table('estimate_lines')
    op.drop_table('estimates')
    op.drop_table('compliance_findings')
    op.drop_table('rfps')
    # ### end Alembic commands ###


